#!/bin/bash

# This script read information from PKGBUILD and builds a .deb package.
# Dependencies: git, svn, curl, unzip, fakeroot, dpkg-deb

# Michal Vlasák, 2020. Public domain.

echo "Sourcing PKGBUILD.."
source PKGBUILD

declare -A archmap
archmap[x86_64]=amd64
arch=${archmap[${arch[0]}]}

pkgdir="${pkgname}_${pkgver}-${pkgrel}_${arch}"
srcdir=src
mkdir -p "$pkgdir" "$srcdir"
pkgdir=$(readlink -f "$pkgdir")
srcdir=$(readlink -f "$srcdir")

if [ -v USE_MAKEPKG_PKG ]; then
	echo "Using what makepkg built."

	# remove makepkg metadata
	rm -rf pkg/lltex/.[A-Z]*

	# change name of package directory so dpkg names result correctly
	rm -rf "$pkgdir"
	mv pkg/lltex "$pkgdir"

	# return back what we moved
else
	echo "Getting sources.."
	cd "$srcdir"
	for src in "${source[@]}"; do
		echo "Getting '$src'"
		case "$src" in
		git+*)
			url=${src##git+}
			ref=${url##*=}
			url=${url%[#@]*}
			dir=${url##*/}

			if [[ ! -d "$dir" ]]; then
				git clone --depth=1 --branch="$ref" -c advice.detachedHead=false "$url" "$dir"
			fi
		;;
		svn*)
			svn checkout "$src"
		;;
		http://*|https://*)
			dest=${src##*/}
			if [[ ! -f "$dest" ]]; then
				curl -fLo "$dest" "$src"
			fi

			case "$dest" in
			*.zip)
				unzip -uo "$dest"
			esac
		;;
		*)
			cp -rf "../$src" .
		esac
	done

	# flags from makepkg.conf
	export CPPFLAGS="-D_FORTIFY_SOURCE=2"
	export CFLAGS="-march=native -O2 -pipe -fno-plt"
	export CXXFLAGS="${CFLAGS}"
	export LDFLAGS="-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now"
	export MAKEFLAGS="-j$(($(nproc)+1))"

	echo "Running build function.."
	build
	echo "Running package function.."
	package

	cd -
fi

echo "Creating Debian metadata."
mkdir -p "$pkgdir/DEBIAN"
cat > "$pkgdir/DEBIAN/control" << EOF
Package: $pkgname
Version: $pkgver
Section: user/hiddewn
Priority: optional
Architecture: $arch
Maintainer: Michal Vlasák <lahcim8@gmail.com>
Description: $pkgdesc
EOF

echo "Creating .deb."
dpkg-deb --root-owner-group -b "$pkgdir"
