#!/bin/sh

set -e

pkgdir=$1
pkgname=$2
# not used
#pkgver=$3

srcdir=$(readlink -f .)

patch() {
	# don't complain if patch is already applied (by previous build)
	command patch -N -p1 "$@" || true
}

install() {
	command install -Dm644 "$@"
}


## PATCH SOURCES

# patch kpathsea
patch -i kpathsea.patch
# patch luaotfload
patch -i luaotfload.patch
# patch luatex
patch -i luatex.patch

## BUILD LUATEX BINARY

# let meson recognize cxx as C file
ln -sf ctangle.cxx ctangle.c
ln -sf common.cxx common.c

if ! [ -f "$pkgdir/usr/bin/mmluatex" ]; then

	meson setup \
	  --prefix        /usr \
	  --libexecdir    lib \
	  --sbindir       bin \
	  --buildtype     plain \
	  --auto-features enabled \
	  --wrap-mode     nodownload \
	  -D              b_lto=true \
	  -D              b_pie=true \
	  builddir

	ninja -C builddir

	DESTDIR=$pkgdir meson install -C builddir

	strip --strip-all "$pkgdir/usr/bin/mmluatex"
else
	rm -rf "$pkgdir/usr/share"
fi


# INSTALL TEX PACKAGES

PATH="$pkgdir/usr/bin:$PATH"
export TEXMF="$pkgdir/usr/share/$pkgname"
export TEXMFDOTDIR

# use docstrip.dtx as docstrip.tex and l3docstrip.tex
ln -sf docstrip.dtx docstrip.tex
ln -sf docstrip.dtx l3docstrip.tex

# generate lipsum.ltd.tex
TEXMFDOTDIR=.:lipsum mmluatex -ini '\let\obeyspaces=\relax \input lipsum.ins'

# generate luamplib.{sty.lua}
TEXMFDOTDIR=.:luamplib mmluatex -ini '\catcode`\{=1 \catcode`\}=2 \let\obeyspaces\relax \input luamplib.dtx'

# generate some lualibs files
TEXMFDOTDIR=.:lualibs mmluatex -ini '\catcode`\{=1 \catcode`\}=2 \let\obeyspaces\relax \input lualibs.dtx'

# install luatex packages
install hyph-utf8/tex/generic/hyph-utf8/patterns/tex/* -t "$TEXMF/tex/hyph-utf8"
install UnicodeData.txt CaseFolding.txt PropList.txt ScriptExtensions.txt Scripts.txt SpecialCasing.txt WordBreakProperty.txt -t "$TEXMF/tex/unicode-data"
install lualibs*.lua lualibs/lualibs*-merged.lua lualibs/*-compat.lua -t "$TEXMF/tex/lualibs"
install luaotfload/luaotfload*.lua luaotfload/fontloader-????-??-??.lua luaotfload/fontloader-basics-gen.lua -t "$TEXMF/tex/luaotfload"
rm -f "$TEXMF/tex/luaotfload/luaotfload-characters.lua"
install luamplib.lua luamplib.sty -t "$TEXMF/tex/luamplib"
install base/*.mp -t "$TEXMF/metapost"

install rsfs/type1/afm/* -t "$TEXMF/fonts/afm"
install rsfs/type1/*.pfb -t "$TEXMF/fonts/type1"

# install optex files
install optex/base/* -t "$TEXMF/tex/optex/base"
install optex/pkg/* -t "$TEXMF/tex/optex/pkg"
install lipsum.sty *.ltd.tex -t "$TEXMF/tex/lipsum"
install hyphen.tex -t "$TEXMF/tex/knuth-lib"

# install our files
install mmoptex.ini -t "$TEXMF/tex/mmoptex"

# run iniluatex to create formats
mmluatex -ini mmoptex.ini

# install format files
install *.fmt -t "$TEXMF/web2c"

# create optex -> luatex symlink
ln -sf mmluatex "$pkgdir/usr/bin/mmoptex"

# create ls-R database
(cd "$TEXMF" && ls -LAR ./ > ls-R)

# copy licenses
licensedir="$pkgdir/usr/share/licenses/$pkgname"
install gpl-2.0.txt "$licensedir/LICENSE.GPLv2"
install lgpl-3.0.txt "$licensedir/LICENSE.LGPLv3"
install lgpl-2.1.txt "$licensedir/LICENSE.LGPLv2.1"
install lppl-1-3c.txt "$licensedir/LICENSE.LPPLv1.3c"
install LICENSE* licenses/LICENSE* -t "$licensedir"
