#!/bin/sh

set -e

pkgdir=$1
pkgname=$2
# not used
#pkgver=$3

srcdir=$(readlink -f .)

install() {
	command install -Dm644 "$@"
}

texmf="$pkgdir/usr/share/mmtex-luatex"

# install pdftex.map
install pdftex.map -t "$texmf/fonts/map"

# there are two manfnt.tfm files, one from cm-tfm package and one from manual package
# use the one from manual package
rm -f tfm/manfnt.tfm
# delete comments and empty lines from .map file, prepare .tfm, .pfb file names
sed -e 's/%.*//' -e '/^$/d' pdftex.map > pdftex.map.tmp
awk '{print "/" $1 ".tfm$"}' pdftex.map.tmp > tfm_files
awk -F'[[:blank:]]|<' '{print "/" $NF "$"}' pdftex.map.tmp > pfb_files
# find all possible font files
find . -type f -regex '.*\.\(tfm\|pfb\)$' > available_files
# install only needed font files
grep -f tfm_files available_files | xargs install -Dm644 -t "$texmf/fonts/tfm"
grep -f pfb_files available_files | xargs install -Dm644 -t "$texmf/fonts/type1"

# run iniluatex to create format file
TEXMF=$texmf TEXMFDOTDIR=".:tex-ini-files:lib" luatex -ini tex-ini-files/luatex.ini

# install format file
install luatex.fmt -t "$texmf/web2c"

# create ls-R database
(cd "$texmf" && ls -LAR ./ > ls-R)
